<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('apartments')->insert([
            // Appartamenti per user_id 1
            [
                'user_id' => 1,
                'title' => 'Appartamento Centrale',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 1,
                'sq_mt' => 100,
                'address' => 'Via Roma, 10, Milano',
                'latitude' => 45.4642,
                'longitude' => 9.1900,
                'images' => 'uploads/apartments/01.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Monolocale Accogliente',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 50,
                'address' => 'Piazza Duomo, 1, Milano',
                'latitude' => 45.4643,
                'longitude' => 9.1905,
                'images' => 'uploads/apartments/02.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Appartamento Vista Lago',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 80,
                'address' => 'Via Lago, 23, Como',
                'latitude' => 45.8103,
                'longitude' => 9.0865,
                'images' => 'uploads/apartments/03.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 2
            [
                'user_id' => 2,
                'title' => 'Bilocale vicino al Duomo',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 70,
                'address' => 'Via Dante, 5, Milano',
                'latitude' => 45.4680,
                'longitude' => 9.1870,
                'images' => 'uploads/apartments/04.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Appartamento Moderno',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 120,
                'address' => 'Via Torino, 15, Milano',
                'latitude' => 45.4640,
                'longitude' => 9.1900,
                'images' => 'uploads/apartments/05.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Attico con Giardino',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 150,
                'address' => 'Via Venezia, 18, Milano',
                'latitude' => 45.4780,
                'longitude' => 9.2080,
                'images' => 'uploads/apartments/06.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 3
            [
                'user_id' => 3,
                'title' => 'Appartamento con Terrazza',
                'rooms_num' => 5,
                'beds_num' => 4,
                'bathroom_num' => 3,
                'sq_mt' => 200,
                'address' => 'Via Vittorio Veneto, 30, Roma',
                'latitude' => 41.9028,
                'longitude' => 12.4964,
                'images' => 'uploads/apartments/07.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Monolocale vicino al Colosseo',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via dei Fori Imperiali, 12, Roma',
                'latitude' => 41.8902,
                'longitude' => 12.4922,
                'images' => 'uploads/apartments/08.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Appartamento con Piscina',
                'rooms_num' => 6,
                'beds_num' => 5,
                'bathroom_num' => 3,
                'sq_mt' => 300,
                'address' => 'Via Appia Antica, 7, Roma',
                'latitude' => 41.8577,
                'longitude' => 12.5216,
                'images' => 'uploads/apartments/09.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 4
            [
                'user_id' => 4,
                'title' => 'Appartamento Vista Mare',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 90,
                'address' => 'Via Lungomare, 12, Napoli',
                'latitude' => 40.8518,
                'longitude' => 14.2681,
                'images' => 'uploads/apartments/10.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Bilocale Storico',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 60,
                'address' => 'Via Toledo, 21, Napoli',
                'latitude' => 40.8479,
                'longitude' => 14.2583,
                'images' => 'uploads/apartments/11.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Trilocale con Vista Vulcano',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 100,
                'address' => 'Via Vesuvio, 5, Napoli',
                'latitude' => 40.8214,
                'longitude' => 14.4265,
                'images' => 'uploads/apartments/12.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 5
            [
                'user_id' => 5,
                'title' => 'Appartamento in Centro Storico',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 120,
                'address' => 'Via Garibaldi, 7, Firenze',
                'latitude' => 43.7696,
                'longitude' => 11.2558,
                'images' => 'uploads/apartments/13.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Monolocale Economico',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via Milano, 50, Genova',
                'latitude' => 44.4056,
                'longitude' => 8.9463,
                'images' => 'uploads/apartments/14.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Appartamento Vista Ponte Vecchio',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 100,
                'address' => 'Via dei Calzaiuoli, 10, Firenze',
                'latitude' => 43.7714,
                'longitude' => 11.2559,
                'images' => 'uploads/apartments/15.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 6
            [
                'user_id' => 6,
                'title' => 'Villa con Giardino',
                'rooms_num' => 5,
                'beds_num' => 4,
                'bathroom_num' => 3,
                'sq_mt' => 200,
                'address' => 'Via delle Rose, 8, Torino',
                'latitude' => 45.0703,
                'longitude' => 7.6869,
                'images' => 'uploads/apartments/16.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Appartamento vicino al Parco',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 130,
                'address' => 'Via Verdi, 2, Torino',
                'latitude' => 45.0703,
                'longitude' => 7.6869,
                'images' => 'uploads/apartments/17.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Trilocale vicino alla Stazione',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 110,
                'address' => 'Via Garibaldi, 7, Torino',
                'latitude' => 45.0705,
                'longitude' => 7.6861,
                'images' => 'uploads/apartments/18.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Appartamenti per user_id 7
            [
                'user_id' => 7,
                'title' => 'Monolocale Economico',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via Milano, 50, Genova',
                'latitude' => 44.4056,
                'longitude' => 8.9463,
                'images' => 'uploads/apartments/19.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Appartamento vicino al Porto',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 60,
                'address' => 'Via del Porto, 5, Genova',
                'latitude' => 44.4066,
                'longitude' => 8.9485,
                'images' => 'uploads/apartments/20.jpg',
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}