<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApartmentSeeder extends Seeder
{
    public function run(): void
    {
        $imagePaths = [
            'uploads/apartments/images (1).jpeg',
            'uploads/apartments/images (2).jpeg',
            'uploads/apartments/images (3).jpeg',
            'uploads/apartments/images (4).jpeg',
            'uploads/apartments/images (5).jpeg',
            'uploads/apartments/images (6).jpeg',
            'uploads/apartments/images (7).jpeg',
            'uploads/apartments/images (8).jpeg',
            'uploads/apartments/images (9).jpeg',
            'uploads/apartments/images (10).jpeg',
            'uploads/apartments/images (11).jpeg',
            'uploads/apartments/images (12).jpeg',
            'uploads/apartments/images (13).jpeg',
            'uploads/apartments/images (15).jpeg',
            'uploads/apartments/images (17).jpeg',
            'uploads/apartments/images (18).jpeg',
            'uploads/apartments/images (19).jpeg',
            'uploads/apartments/images (20).jpeg',
            'uploads/apartments/images (21).jpeg',
            'uploads/apartments/images (22).jpeg',
            'uploads/apartments/images (23).jpeg',
            'uploads/apartments/images (24).jpeg',
            'uploads/apartments/images (25).jpeg',
            'uploads/apartments/images (26).jpeg',
            'uploads/apartments/images (27).jpeg',
            'uploads/apartments/images (28).jpeg',
            'uploads/apartments/images (29).jpeg',
            'uploads/apartments/images (30).jpeg',
            'uploads/apartments/images (32).jpeg',
            'uploads/apartments/images (33).jpeg',
            'uploads/apartments/images (34).jpeg',
            'uploads/apartments/images (35).jpeg',
            'uploads/apartments/images (36).jpeg',
            'uploads/apartments/images (37).jpeg',
            'uploads/apartments/images (38).jpeg',
        ];


        $getRandomImage = function () use ($imagePaths) {
            return $imagePaths[array_rand($imagePaths)];
        };

        DB::table('apartments')->insert([
            [
                'user_id' => 1,
                'title' => 'Appartamento Centrale',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 1,
                'sq_mt' => 100,
                'address' => 'Via Roma, 10, Milano',
                'latitude' => 45.4642,
                'longitude' => 9.1900,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Monolocale Accogliente',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 50,
                'address' => 'Piazza Duomo, 1, Milano',
                'latitude' => 45.4643,
                'longitude' => 9.1905,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Appartamento Vista Lago',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 80,
                'address' => 'Via Lago, 23, Como',
                'latitude' => 45.8103,
                'longitude' => 9.0865,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Appartamento Confortevole',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 95,
                'address' => 'Via Del Mare, 15, Milano',
                'latitude' => 45.4680,
                'longitude' => 9.1890,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Appartamento Tranquillo',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 80,
                'address' => 'Via Libertà, 18, Milano',
                'latitude' => 45.4640,
                'longitude' => 9.1820,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Bilocale vicino al Duomo',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 70,
                'address' => 'Via Dante, 5, Milano',
                'latitude' => 45.4680,
                'longitude' => 9.1870,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Appartamento Moderno',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 120,
                'address' => 'Via Torino, 15, Milano',
                'latitude' => 45.4640,
                'longitude' => 9.1900,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Attico con Giardino',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 150,
                'address' => 'Via Venezia, 18, Milano',
                'latitude' => 45.4780,
                'longitude' => 9.2080,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Monolocale Moderno',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 50,
                'address' => 'Via Manzoni, 9, Milano',
                'latitude' => 45.4720,
                'longitude' => 9.1920,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Bilocale Vista Parco',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 60,
                'address' => 'Via Parco, 2, Milano',
                'latitude' => 45.4620,
                'longitude' => 9.2000,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Appartamento con Terrazza',
                'rooms_num' => 5,
                'beds_num' => 4,
                'bathroom_num' => 3,
                'sq_mt' => 200,
                'address' => 'Via Vittorio Veneto, 30, Roma',
                'latitude' => 41.9028,
                'longitude' => 12.4964,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Monolocale vicino al Colosseo',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via dei Fori Imperiali, 12, Roma',
                'latitude' => 41.8902,
                'longitude' => 12.4922,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Appartamento con Piscina',
                'rooms_num' => 6,
                'beds_num' => 5,
                'bathroom_num' => 3,
                'sq_mt' => 300,
                'address' => 'Via Appia Antica, 7, Roma',
                'latitude' => 41.8577,
                'longitude' => 12.5216,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Appartamento di Lusso',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 160,
                'address' => 'Via Margutta, 1, Roma',
                'latitude' => 41.9087,
                'longitude' => 12.4769,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Appartamento Classico',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 140,
                'address' => 'Via del Corso, 23, Roma',
                'latitude' => 41.9027,
                'longitude' => 12.4831,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Appartamento Vista Mare',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 90,
                'address' => 'Via Lungomare, 12, Napoli',
                'latitude' => 40.8518,
                'longitude' => 14.2681,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Bilocale Storico',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 60,
                'address' => 'Via Toledo, 21, Napoli',
                'latitude' => 40.8479,
                'longitude' => 14.2583,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Trilocale con Vista Vulcano',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 100,
                'address' => 'Via Vesuvio, 5, Napoli',
                'latitude' => 40.8214,
                'longitude' => 14.4265,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Appartamento Luminoso',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 120,
                'address' => 'Via Partenope, 18, Napoli',
                'latitude' => 40.8418,
                'longitude' => 14.2620,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Monolocale Economico',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via San Carlo, 5, Napoli',
                'latitude' => 40.8379,
                'longitude' => 14.2505,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Appartamento in Centro Storico',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 120,
                'address' => 'Via Garibaldi, 7, Firenze',
                'latitude' => 43.7696,
                'longitude' => 11.2558,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Monolocale Economico',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via Milano, 50, Genova',
                'latitude' => 44.4056,
                'longitude' => 8.9463,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Appartamento Vista Ponte Vecchio',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 100,
                'address' => 'Via dei Calzaiuoli, 10, Firenze',
                'latitude' => 43.7714,
                'longitude' => 11.2559,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Appartamento Ristrutturato',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 80,
                'address' => 'Via della Scala, 12, Firenze',
                'latitude' => 43.7760,
                'longitude' => 11.2498,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'Bilocale Elegante',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 75,
                'address' => 'Via Tornabuoni, 5, Firenze',
                'latitude' => 43.7710,
                'longitude' => 11.2511,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Villa con Giardino',
                'rooms_num' => 5,
                'beds_num' => 4,
                'bathroom_num' => 3,
                'sq_mt' => 200,
                'address' => 'Via delle Rose, 8, Torino',
                'latitude' => 45.0703,
                'longitude' => 7.6869,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Appartamento vicino al Parco',
                'rooms_num' => 4,
                'beds_num' => 3,
                'bathroom_num' => 2,
                'sq_mt' => 130,
                'address' => 'Via Verdi, 2, Torino',
                'latitude' => 45.0703,
                'longitude' => 7.6869,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Trilocale vicino alla Stazione',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 110,
                'address' => 'Via Garibaldi, 7, Torino',
                'latitude' => 45.0705,
                'longitude' => 7.6861,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Appartamento Moderno',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 1,
                'sq_mt' => 100,
                'address' => 'Via Monte Bianco, 20, Torino',
                'latitude' => 45.0652,
                'longitude' => 7.6780,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Monolocale Centrale',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 50,
                'address' => 'Via Po, 15, Torino',
                'latitude' => 45.0654,
                'longitude' => 7.6847,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Monolocale Economico',
                'rooms_num' => 1,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 40,
                'address' => 'Via Milano, 50, Genova',
                'latitude' => 44.4056,
                'longitude' => 8.9463,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Appartamento vicino al Porto',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 60,
                'address' => 'Via del Porto, 5, Genova',
                'latitude' => 44.4066,
                'longitude' => 8.9485,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Bilocale Ristrutturato',
                'rooms_num' => 2,
                'beds_num' => 1,
                'bathroom_num' => 1,
                'sq_mt' => 75,
                'address' => 'Via del Mare, 10, Genova',
                'latitude' => 44.4072,
                'longitude' => 8.9495,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Appartamento Vista Mare',
                'rooms_num' => 3,
                'beds_num' => 2,
                'bathroom_num' => 2,
                'sq_mt' => 90,
                'address' => 'Via della Lanterna, 12, Genova',
                'latitude' => 44.4080,
                'longitude' => 8.9510,
                'images' => $getRandomImage(),
                'visibility' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
